### PR TITLE
CHEMC-16 Sort sections by delta

### PR DESCRIPTION
**Pull request by juampynr**
## Testing instructions
1. Checkout this branch.
2. Run `drush fr --yes --force luggage_courses`.
3. Edit a course. Add sections in a particular order. Save.
   image
4. Verify that when viewing the course, the list of sections matches
   the given order.
   image

### CODE REVIEW

**Comment by agreazel** [comment]
I tested a course that already existed and altered the order of the sections and saved. The order changed correctly.
screen shot 2015-07-27 at 10 06 41 am
screen shot 2015-07-27 at 10 07 08 am

Then, I created a new course as a test for Spring 2016 Graduate; the section orders on this course did not get updated properly in the display when I altered them. However, the related courses worked when I altered the order of related courses.
screen shot 2015-07-27 at 10 13 54 am
screen shot 2015-07-27 at 10 14 18 am

**Comment by juampynr** [comment]
@agreazel, I followed your steps but I can't reproduce the issue that you describe. Did you click on Save after reordering sections? I sometimes forget to do so, hence my question:

image

Here is exactly what I tried:
1. Edit course "erat propious"
2. Add related sections to the middle >> checked that the order matches after saving.
3. View a course where "erat propious" is related >> checked that the order matched.

Then I created a new course, where I added a few sections and related courses and dragged them up and down to change their order. Clicked Save in a way that it would open the result in a new tab so I could compare the order or both listings and they both matched. Am I missing something?

**Comment by agreazel** [comment]
screen shot 2015-07-28 at 8 44 57 am
screen shot 2015-07-28 at 8 44 39 am

@juampy72 this is exactly what I tried:
1. live to local of chemcourses site
2. Edited course "Chemistry for Engineering Students"
3. The sections were in proper order on the edit screen of A, B, C, D.
4. Saved
5. Order of sections displayed is D, C, B, A.

**Comment by agreazel** [comment]
oops. aparently it was a user error. I forgot to use --all

**Pull request merged**
